version: "3.9"
services:
  server:
    build: ./backend
    ports:
    - "3000:3000"
    volumes:
    - ./backend:/app/backend
  frontend:
    build: ./frontend
    ports:
    - "5173:5173"
    volumes:
    - ./frontend:/app/frontend